version: '3.7'
services:
  hapi:
    image: "hapiproject/hapi"
    ports:
      - ${FHIR_SERVER_PORT}:8080
    environment:
      hapi.fhir.tester.home.server_address: http://host.docker.internal:${FHIR_SERVER_PORT}/fhir
