version: '3.7'
services:
  hapi:
    image: "hapiproject/hapi"
    ports:
      - ${FHIR_SERVER_PORT}:8080
#    volumes:
#      - ./config/hapi:/data/hapi
    environment:
      hapi.fhir.tester.home.server_address: http://host.docker.internal:${FHIR_SERVER_PORT}/fhir
#      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
